version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mi-lab-ldh-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log-error-verbosity=1
    restart: always
    stop_grace_period: 1m30s
    env_file:
      - .env
    volumes:
      - mi-lab-ldh-mysql-db:/var/lib/mysql

  seek: # The SEEK application
    image: fairdom/seek:seek-1.15-fhir-api
    container_name: mi-lab-ldh
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
      SOLR_PORT: 8983
      SOLR_HOST: solr
      NO_ENTRYPOINT_WORKERS: 1
    env_file:
      - .env
    volumes:
      - mi-lab-ldh-filestore:/seek/filestore
      - mi-lab-ldh-cache:/seek/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
    links:
      - db
      - solr

  seek_workers: # The SEEK delayed job workers
      image: fairdom/seek:seek-1.15-fhir-api
      container_name: mi-lab-ldh-workers
      command: docker/start_workers.sh
      restart: always
      environment:
        RAILS_ENV: production
        SOLR_PORT: 8983
        SOLR_HOST: solr
      env_file:
        - .env
      volumes:
        - mi-lab-ldh-filestore:/seek/filestore
        - mi-lab-ldh-cache:/seek/tmp/cache
      depends_on:
        - db
        - solr
      links:
        - db
        - solr

  solr:
    image: fairdom/seek-solr:8.11
    container_name: mi-lab-ldh-solr
    restart: always
    environment:
      SOLR_JAVA_MEM: -Xms512m -Xmx1024m
    volumes:
      - mi-lab-ldh-solr-data:/var/solr/
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - seek
      - /opt/solr/server/solr/configsets/seek_config      


volumes:
  mi-lab-ldh-filestore:
    external: true
  mi-lab-ldh-mysql-db:
    external: true
  mi-lab-ldh-solr-data:
    external: true
  mi-lab-ldh-cache:
    external: true

